blank_issues_enabled: false
contact_links:
  - name: Tower Guard Documentation
    url: https://guard-core.github.io/tower-guard-rs/
    about: Check the documentation for usage information and tutorials
  - name: Usage Questions
    url: https://github.com/Guard-Core/tower-guard-rs/discussions
    about: Please ask and answer questions in GitHub Discussions
  - name: Discord
    url: https://discord.gg/ZW7ZJbjMkK
    about: Questions and support in #help, new versions in #releases, development stream in #dev-feed
